### ISSUE TITLE
BUG: unresolved import `std::hash::DefaultHasher` after update to 0.5.0

### ISSUE THREAD

**Issue by pberck** [oasysai/oasysdb#87]
### Short description

Updated from oasysdb 0.4.4 to 0.5.0. Building my program now gives this error:
```shell
--> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/oasysdb-0.5.0/src/db/mod.rs:9:17
  |
9 | use std::hash::{DefaultHasher, Hash, Hasher};
  |                 ^^^^^^^^^^^^^ no `DefaultHasher` in `hash`
  |
  = help: consider importing this struct instead:
          std::collections::hash_map::DefaultHasher

For more information about this error, try `rustc --explain E0432`.
error: could not compile `oasysdb` (lib) due to previous error
```
Compiling on a M1 MacBookPro.

**Comment by edwinkys** [comment]
Hey 👋
Thank you for using OasysDB and sorry for the inconvenience.

Could you share the Rust version you’re running for your project?

    rustc --version

According to the [official documentation](https://doc.rust-lang.org/stable/std/hash/struct.DefaultHasher.html), the `std::hash::DefaultHasher` should be available from version 1.7.0.

**Comment by pberck** [comment]
Sure, the version is:
```text
rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
```

**Comment by edwinkys** [comment]
Thank you! That's pretty new and should work with OasysDB.
Well, I can implement the fix and make a release tomorrow.
Once again, sorry for the inconvenience.

**Comment by durian** [comment]
No problem!
Thanks for the quick fix!

**Comment by pberck** [comment]
No problem!
Thanks for the quick fix!

**Comment by edwinkys** [comment]
Hey, I just make a release of 0.5.1 to introduce the fix for you.
Let me know if it works 😁

**Comment by edwinkys** [comment]
I will close this issue as this should be fixed with the v0.5.1 release.
If there is something wrong with this fix, please let me know 😁

**Comment by pberck** [comment]
Works now, thanks!
